---
  - hosts: 51.140.162.76
    become: true
    tasks:
    - name: Install JAVA
      apt:
        name: openjdk-8-jdk
        state: latest
        update_cache: true
    - name: Add Jenkins repo key
      apt_key:
        url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"
        state: present
    - name: Add Jenkins repo
      apt_repository:
        repo: "deb http://pkg.jenkins.io/debian-stable binary/"
        state: present
        # update_cache: true
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
          # update_cache: true
    - name: Start Jenkins
      service:
        name: jenkins
        state: started